apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-directory
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/applications
    repoURL: https://github.com/zogot/homelab.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true