apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddclient
  namespace: {{.Release.Namespace}}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          restartPolicy: Never
          containers:
            - name: ddclient
              image: "lscr.io/linuxserver/ddclient:latest"
              command:
                - ddclient
              args:
                - -daemon=0
                - -debug
                - -noquiet
                - -cache
                - "/tmp/ddclient/ddclient.cache"
              env:
                - name: PUID
                  value: "1000"
                - name: PGID
                  value: "1000"
                - name: TZ
                  value: Europe/Amsterdam
                - name: DDCLIENT_LOGIN
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-api-key
                      key: username
                - name: DDCLIENT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-api-key
                      key: global
              volumeMounts:
                - mountPath: /config
                  name: config
                  subPath: ddclient.conf
                - mountPath: /tmp/ddclient
                  name: cache
          volumes:
            - name: config
              configMap:
                name: ddclient-config
            - name: cache
              persistentVolumeClaim:
                claimName: ddclient-cache

