apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddclient-cache
  namespace: {{.Release.Namespace}}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
