apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-helm
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: https://github.com/zogot/homelab.git
        revision: HEAD
        directories:
          - path: argocd/helm/*
  template:
    metadata:
      name: '{{.path.basename}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/zogot/homelab.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          releaseName: "{{.path.basename}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

