apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-pihole
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repository: "https://kubernetes-sigs.github.io/external-dns"
    targetRevision: 1.14.4
    helm:
      releaseName: external-dns-pihole
      valuesObject:
        deploymentAnnotations:
          operator.1password.io/item-path: "vaults/Jupiter/items/PiHole"
          operator.1password.io/item-name: "pihole-password"
        provider:
          name: pihole
        env:
          - name: EXTERNAL_DNS_PIHOLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pihole-password
                key: password
        registry: noop
        sources:
          - ingress
        extraArgs:
          - --pihole-server=http://192.168.100.80
          - --ingress-class=external
          - --ingress-class=internal
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true