apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
spec:
  project: default
  source:
    chart: connect
    repoURL: "https://1password.github.io/connect-helm-charts"
    targetRevision: 1.15.0
    helm:
      releaseName: onepassword-connect
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
