apiVersion: v2
name: longhorn
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: longhorn
    repository: https://charts.longhorn.io
    version: v1.6.2
