deploymentAnnotations:
  operator.1password.io/item-path: "vaults/${vault}/items/${item}"
  operator.1password.io/item-name: "pihole-password"

provider:
  name: pihole

env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password

registry: noop

sources:
  - ingress

extraArgs:
  - --pihole-server=${server}
  - --ingress-class=external
  - --ingress-class=internal
